name: CICD
on:
  push:
    branches: [dev, master]

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: us-east-1
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install serverless
        run: npm install -g serverless

      - name: Install dependencies
        run: npm install

      - name: Lint
        run: npm run lint

      - name: Deploy - Development
        if: endsWith(github.ref, '/dev')
        run: serverless deploy

      - name: Deploy - Production
        if: endsWith(github.ref, '/master')
        run: serverless deploy --stage prod
